### ISSUE TITLE
MIT

### ISSUE THREAD

**Issue by nanjizal** [sgalland/bmpfont#3]
why did you not publish this and the 'compiler' as MIT or dual license, I really not sure many in Haxe community will use it with GPL license. 
For instance impossible to use with hxTrueType etc... given the size of that library and yours it's easier to recreate an alternate bitmap font approach.  But maybe my perspective - I try to release everything as MIT.

Best Justin

**Comment by sgalland** [comment]
I am not opposed to the MIT license. I assumed that GPL would be good enough but it looks like much of the haxelibs are licensed more permissively.

**Comment by sgalland** [comment]
Changed license to MIT

**Comment by nanjizal** [comment]
noticed in your data package some typedef.  I have found faster even on JS to use @:structInit

https://code.haxe.org/category/beginner/declare-classes-with-structinit.html

and normally you don't need to make any mod to other parts of the code when side grading typedef's for structs, for any extra functionality like special trace functions for debugging I often add them with an abstract wrapper.

**Comment by sgalland** [comment]
#4
